# Generated by Django 4.2 on 2023-04-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=25, max_digits=30)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_stamp'],
            },
        ),
    ]
