# Generated by Django 4.2 on 2023-04-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='user_placeholder.svg', upload_to='static/images/profile_pictures'),
        ),
    ]
